### ISSUE TITLE
purge jsdelivr cache in CI/CD

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#1090]
## Problem

Bugfixes are not rolled out immediately.

https://github.com/inlang/inlang/issues/1082#issuecomment-1635451236

## Proposal

Purge JSDelivr cache in CI/CD after updating a plugin.

**Comment by NilsJacobsen** [comment]
Done with https://github.com/inlang/inlang/commit/d56944887da7fe241b1b342aa20e265ae9b02917

**Comment by NilsJacobsen** [comment]
Do you guys know if we can point to the latest major version?

Current:
```yml
  purge-jsdelivr-cache:
    runs-on: ubuntu-latest
    steps:
      # purge all plugins, needs to be updated after maijor version bumps
      - uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/npm/@inlang/plugin-i18next@3/dist/index.js
            https://cdn.jsdelivr.net/npm/@inlang/plugin-json@3/dist/index.js
            https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@3/dist/index.js
```
