### ISSUE TITLE
release process is broken 

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2055]
## Problem 

1. Merging a versioning PR like https://github.com/opral/monorepo/pull/2054 does not update the package lock. 
2. Subsequently, deploys in CI/CD are failing because the package lock is not updating. 
3. A manual package lock update is required https://github.com/opral/monorepo/commit/9d8feb884693fd629ed576e0dccac45d977006ff

## Proposal 

Automate the package lock update with versioning

**Comment by samuelstroschein** [comment]
I will evaluate if #2039 is fixing this

**Comment by samuelstroschein** [comment]
Wild now PNPM breaks in github actions but not in render deployment. Everything seems OK though. Will evaluate tmr as part of #2039

**Comment by LorisSigrist** [comment]
The PNPM package lock not being updated seems to be a known issue [changesets/changesets#421](https://github.com/changesets/changesets/issues/421). The creator of PNPM recommends [this workaround](https://github.com/changesets/changesets/issues/421#issuecomment-667915114)

> Wild now PNPM breaks in github actions but not in render deployment. Everything seems OK though. Will evaluate tmr as part of https://github.com/opral/monorepo/issues/2039

This is likely because PNPM doesn't recognize Render as a CI environment so it doesn't use the lockfile. Instead it does a regular `pnpm install` like it would on a developer's machine. We should probably fix this, as we could end up with different versions of our dependencies in CI and Production.

**Comment by samuelstroschein** [comment]
@LorisSigrist render is detected as CI environment. Issues like this one (https://github.com/changesets/changesets/issues/421) are what I mean by changesets is unmaintained. Open for 4 years, needs workarounds to make this work.

**Comment by openscript** [comment]
I've updated my workflow to this:

```yaml
name: Version packages

on:
  push:
    branches:
      - main

jobs:
  version-packages:
    name: Version packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request
        uses: changesets/action@v1
        id: changesets
        with:
          commit: "chore: publish new release"
          title: "chore: publish new release"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Update lock file
        run: pnpm install --lockfile-only

      - name: Commit lock file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update lock file"
          branch: changeset-release/main
```
